### ISSUE TITLE
Shadows have become broken

### ISSUE THREAD

**Issue by DoctorAnsem** [SleepKiller/shaderpatch#74] opened 2019-07-06 10:20 UTC
[As shown here](https://drive.google.com/open?id=1S8k_SVMJUML3vBqOoFjRvjAwEA5b-9nZ), the latest build seems to have issues with shadows. As far as I can tell, it doesn't seem like it's tied to any specific effect except maybe HDR but I say that just because I didn't test if it happens without.

**Comment by SleepKiller** [comment] 2019-07-06 12:39
I've had other people report a similar bug as well. I was never able to reproduce it but in their cases it was fixed by setting `Allow Tearing` to `no` (In the next preview of v1.1 it'll actually be set to no by default because of it 14a1088222880ee3807564803a0f7f6c79f19f4b), think you could give setting it to no a go and see if it solves it?

**Comment by DoctorAnsem** [comment] 2019-07-06 13:47
Hm, well. It caused a couple things to happen. It did fix the shadows, however, it also gave me a choppy framerate and made the SP interface unresponsive again. 

Also this gave me an idea for a tiny request: since shader patch can now control which GPU it uses, would it be possible to make it print in the log which one it does?

**Closed** 2019-10-06 15:12 UTC
