### ISSUE TITLE
Certain lights flicker/render incorrectly

### ISSUE THREAD

**Issue by auri0n** [SleepKiller/shaderpatch#26] opened 2018-08-17 16:13 UTC
This problem occurs when effects are enabled and disabled, but is much more noticeable when HDR rendering is turned on. I don't believe this was present until the 0.8.x releases. Here are a few short clips highlighting the issue:

Two with HDR disabled (https://i.imgur.com/y5qYlHC.mp4) (https://i.imgur.com/OycHcKf.mp4)

and another with it enabled (https://i.imgur.com/w3b5hgR.mp4).

Lens flares have a similar problem; they tend to flicker instead of fading out smoothly when covered by something (https://i.imgur.com/YGx4pRc.mp4).

Sometimes they fade out correctly, though (https://i.imgur.com/OEDUGYd.mp4).

**Comment by SleepKiller** [comment] 2018-08-18 07:46
Thanks for the detailed report. I suspect this is being caused by a [hack](https://github.com/SleepKiller/swbfii-shaderpatch/blob/eca164e6cdeb7af3cb74201cd45906dec9b012eb/assets/core/src/sample.fx#L36) that let's SP use R10G10B10A2 formats to significantly reduce colour banding (when Effects are active) in some situations. 

I feel this is a worthwhile tradeoff but it'd be better if it wasn't needed at all. I think it should be possible to fix it as the render targets used with the [sample](https://github.com/SleepKiller/swbfii-shaderpatch/blob/master/assets/core/src/sample.fx) shader probably don't need to be the same as the ones being used for the rest of drawing, which should mean it's possible to just have it use R8G8B8A8 targets which would remove the need for the hack. Or it might be possible to just use a different channel than the alpha one in flare and sample shaders, which would also remove the need for the hack.

In either event it would solve the problem without further compromise. Hopefully I'll have it fixed in the next version

**Comment by SleepKiller** [comment] 2019-03-23 12:40
[v1.0.0](https://github.com/SleepKiller/shaderpatch/releases/tag/v1.0.0-rc.0) should've resolve this.

**Closed by SleepKiller** 2019-03-23 12:40 UTC
Labels: bug
