### ISSUE TITLE
Galactic Conquest Bug

### ISSUE THREAD

**Issue by Calrissian97** [SleepKiller/shaderpatch#44] opened 2019-03-24 02:27 UTC
Whenever the effects system is active the colors and planet effects aren't rendered. (Workaround is disabling shadows)

**Comment by SleepKiller** [comment] 2019-03-28 04:27
I can't reproduce this anymore. Can you verify if the fix for #43 resolved this as well?

**Comment by SleepKiller** [comment] 2019-05-22 02:47
I'm going to go a head and close this to help keep the issues clean. I'm pretty sure this should've been fixed, if it hasn't just reopen it.

**Closed by SleepKiller** 2019-05-22 02:47 UTC
Labels: bug
